/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 14/03/2012, 02:40:44
 */
package iged.gui;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dorgi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static TelaPrincipal novaTela;

    /** Creates new form TelaPrincipal */
    private TelaPrincipal() {
        initComponents();
    }

    public static TelaPrincipal getInstance() {
        if (novaTela == null) {
            novaTela = new TelaPrincipal();
        }
        return novaTela;
    }

    public JPanel getPanel() {
        return getInstance().panelPrincipal;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        botaoCadastrarTutorial = new javax.swing.JButton();
        botaoAbrir = new javax.swing.JButton();
        botaoVisualizarTutorial = new javax.swing.JButton();
        botaoCadastrarExercicio = new javax.swing.JButton();
        botaoResponderExercicio = new javax.swing.JButton();
        botaoSobre = new javax.swing.JButton();
        botaoAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IGED - Interpretador de Comandos e Avaliador Gráfico para o Ensino de Estrutura de Dados");
        setResizable(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        botaoCadastrarTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/49.png"))); // NOI18N
        botaoCadastrarTutorial.setText("Cadastrar Tutorial");
        botaoCadastrarTutorial.setToolTipText("Cadastrar Tutorial");
        botaoCadastrarTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarTutorialActionPerformed(evt);
            }
        });

        botaoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/119.png"))); // NOI18N
        botaoAbrir.setText("Abrir Arquivo");
        botaoAbrir.setToolTipText("Abrir Arquivo");
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });

        botaoVisualizarTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10.png"))); // NOI18N
        botaoVisualizarTutorial.setText("Visualizar Tutorial");
        botaoVisualizarTutorial.setToolTipText("Visualizar Tutorial");
        botaoVisualizarTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarTutorialActionPerformed(evt);
            }
        });

        botaoCadastrarExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/37.png"))); // NOI18N
        botaoCadastrarExercicio.setText("Cadastrar Exercício");
        botaoCadastrarExercicio.setToolTipText("Cadastrar Exercício");
        botaoCadastrarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarExercicioActionPerformed(evt);
            }
        });

        botaoResponderExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        botaoResponderExercicio.setText("Responder Exercício");
        botaoResponderExercicio.setToolTipText("Responder Exercício");
        botaoResponderExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResponderExercicioActionPerformed(evt);
            }
        });

        botaoSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/13.png"))); // NOI18N
        botaoSobre.setText("Sobre");
        botaoSobre.setToolTipText("Sobre o IGED");
        botaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreActionPerformed(evt);
            }
        });

        botaoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/67.png"))); // NOI18N
        botaoAjuda.setText("Ajuda");
        botaoAjuda.setToolTipText("Ajuda");
        botaoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAbrir)
                        .addGap(2, 2, 2)
                        .addComponent(botaoCadastrarTutorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVisualizarTutorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrarExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoResponderExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSobre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAjuda))
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAbrir)
                    .addComponent(botaoCadastrarTutorial)
                    .addComponent(botaoVisualizarTutorial)
                    .addComponent(botaoCadastrarExercicio)
                    .addComponent(botaoResponderExercicio)
                    .addComponent(botaoSobre)
                    .addComponent(botaoAjuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JInternalFrame cadTutorial, cadExe, visualizarTut, responderExe;

    private void botaoVisualizarTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarTutorialActionPerformed
        if (visualizarTut == null) //instancia a tela de cadastro de clientes
        {
            visualizarTut = new TelaTocadorInterno();
            jDesktopPane1.add(visualizarTut);
            visualizarTut.setClosable(true);
            visualizarTut.setMaximizable(true);
            visualizarTut.setIconifiable(true);
            visualizarTut.show();
        }
        //independente da tela estar visível ou não, a tela é movida para frente
        jDesktopPane1.moveToFront(visualizarTut);
    }//GEN-LAST:event_botaoVisualizarTutorialActionPerformed

    private void botaoResponderExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResponderExercicioActionPerformed
        if (responderExe == null) //instancia a tela de cadastro de clientes
        {
            responderExe = new TelaExercicioInterno();
            jDesktopPane1.add(responderExe);
            responderExe.setClosable(true);
            responderExe.setMaximizable(true);
            responderExe.setIconifiable(true);
            responderExe.show();
        }
        //independente da tela estar visível ou não, a tela é movida para frente
        jDesktopPane1.moveToFront(responderExe);
    }//GEN-LAST:event_botaoResponderExercicioActionPerformed

    private void botaoCadastrarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarExercicioActionPerformed
        if (cadExe == null) //instancia a tela de cadastro de clientes
        {
            cadExe = new TelaCadastroDeTarefaInterno();
            jDesktopPane1.add(cadExe);
            cadExe.setClosable(true);
            cadExe.setMaximizable(true);
            cadExe.setIconifiable(true);
            cadExe.show();
        }
        //independente da tela estar visível ou não, a tela é movida para frente
        jDesktopPane1.moveToFront(cadExe);
    }//GEN-LAST:event_botaoCadastrarExercicioActionPerformed

    private void botaoCadastrarTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarTutorialActionPerformed
        if (cadTutorial == null) //instancia a tela de cadastro de clientes
        {
            cadTutorial = new TelaCadastroDeTutorialInterno();
            jDesktopPane1.add(cadTutorial);
            cadTutorial.setClosable(true);
            cadTutorial.setMaximizable(true);
            cadTutorial.setIconifiable(true);
            cadTutorial.show();
        }
        //independente da tela estar visível ou não, a tela é movida para frente
        jDesktopPane1.moveToFront(cadTutorial);
    }//GEN-LAST:event_botaoCadastrarTutorialActionPerformed

    private void botaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreActionPerformed
        JOptionPane.showMessageDialog(this, "Interpretador de Comandos e Avaliador Gráfico para o Ensino de Estrutura de Dados!\n Versão 1.0");
    }//GEN-LAST:event_botaoSobreActionPerformed

    private void botaoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaActionPerformed
        JOptionPane.showMessageDialog(this, "Ajuda Indisponível!");
    }//GEN-LAST:event_botaoAjudaActionPerformed

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        JFileChooser jfc = new JFileChooser();
        File swingFile = new File("C:\\Users\\Public\\Documents\\");
        if (swingFile.exists()) {
            jfc.setCurrentDirectory(swingFile);
            jfc.setSelectedFile(swingFile);
        }

        //Permite selecionar vários arquivos
        jfc.setMultiSelectionEnabled(true);
        File[] file = jfc.getSelectedFiles();

        //Cria o filtro
        jfc.setFileFilter(new javax.swing.filechooser.FileFilter() {

            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".iged") || f.isDirectory();
            }
            //Mensagem exibida para o usuário

            public String getDescription() {
                return "Arquivos de imagem (.iged)";
            }
        });
        //FileChooser com botão para salvar
        //jfc.showSaveDialog(this);
        //Alterar o título da janela
        jfc.setDialogTitle("Abrir apresentacao");

        int retorno = jfc.showOpenDialog(null);
        //JOptionPane.showMessageDialog(this,"Funcionalidade ainda não implementada!");
    }//GEN-LAST:event_botaoAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                gd.setFullScreenWindow(TelaPrincipal.getInstance());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbrir;
    private javax.swing.JButton botaoAjuda;
    private javax.swing.JButton botaoCadastrarExercicio;
    private javax.swing.JButton botaoCadastrarTutorial;
    private javax.swing.JButton botaoResponderExercicio;
    private javax.swing.JButton botaoSobre;
    private javax.swing.JButton botaoVisualizarTutorial;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
