/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpb.iged.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.TexturePaint;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author darkolyver
 */
public class Background extends javax.swing.JPanel {

    BufferedImage b;  
    Rectangle2D rect; 
        
    public Background() {
        try {
            //se você pegar uma imagem dentro do mesmo jar/projeto  
            b = ImageIO.read(getClass().getResourceAsStream("imagens/99.png"));

            //ou, se você pegar uma imagem direto do sistema, use este                 
            // b = ImageIO.read(new File("<caminho da imagem>"));  

            //cria uma imagem do tamanho 130x130,   
            //que vai se repetir ao longo do fundo, o tamanho é você quem escolhe.  
            rect = new Rectangle(0, 0, 130, 130);

        } catch (IOException ex) {
            ex.printStackTrace(System.err);
        }

    }

    @Override
    protected void paintComponent(Graphics g) {

        TexturePaint p = new TexturePaint(b, rect);
        Graphics2D g2 = (Graphics2D) g;
        g2.setPaint(p);
        g2.fillRect(0, 0, this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
