package br.ufpb.iged.gui;

import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Label;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author renanoliveira
 */
public class TelaCadastroSequenciaDidatic extends javax.swing.JFrame {

    private ImageIcon img;
    private Image images;
    private String diretorioArqSel;
    private Container container = this.getContentPane();
    private BufferedImage buffer;


    /**
     * Creates new form TelaCadastroSequenciaDidatic
     */
    public TelaCadastroSequenciaDidatic() {
        initComponents();
        this.setLocationRelativeTo(null);
             
        images = Toolkit.getDefaultToolkit().getImage("/home/renanoliveira/Imagens/IMG_7786.JPG");
        
        MediaTracker tracker = new MediaTracker(this);
        tracker.addImage(images, 0);
        try {
            tracker.waitForID(0);
        } catch (InterruptedException e) {
            
        }
        setSize(images.getWidth(this), images.getHeight(this));
        buffer = new BufferedImage(images.getWidth(this), images.getHeight(this), BufferedImage.TYPE_INT_RGB);
        Graphics gb = buffer.createGraphics();
        gb.drawImage(images, 0, 0, this);
        
        panelImagens.add(new JLabel(new ImageIcon(images)));
        
        panelImagens.repaint();
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagens = new javax.swing.JPanel();
        btnProximo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnCarregarImagens = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagens.setBorder(javax.swing.BorderFactory.createTitledBorder("Slide"));

        javax.swing.GroupLayout panelImagensLayout = new javax.swing.GroupLayout(panelImagens);
        panelImagens.setLayout(panelImagensLayout);
        panelImagensLayout.setHorizontalGroup(
            panelImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        panelImagensLayout.setVerticalGroup(
            panelImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        btnProximo.setText("Próximo");

        btnAnterior.setText("Anterior");

        btnCarregarImagens.setText("Carregar Imagens");
        btnCarregarImagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarregarImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarImagensActionPerformed(evt);
            }
        });

        jButton4.setText("Gerar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCarregarImagens)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelImagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnterior, btnProximo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnAnterior)
                    .addComponent(btnCarregarImagens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarImagensActionPerformed
                        
        JFileChooser jFileChooser = new JFileChooser();
        File arq;
        File[] selecionados;

        File swingFile = new File("C:\\Users\\Dorgi");
        if (swingFile.exists()) {
            jFileChooser.setCurrentDirectory(swingFile);
            jFileChooser.setSelectedFile(swingFile);
        }

        //Permite selecionar vários arquivos
        jFileChooser.setMultiSelectionEnabled(true);

        //Cria o filtro para aceitar apenas arquivos jpg
        jFileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".jpg") || f.isDirectory();
            }
            //Mensagem exibida para o usuário

            public String getDescription() {
                return "Arquivos de imagem (.jpg)";
            }
        });

        //FileChooser com botão para salvar
        //jfc.showSaveDialog(this);

        //Alterar o título da janela
        jFileChooser.setDialogTitle("Abrir apresentacao");


        //CamposXML c = new CamposXML();

        //Selecionar arquivo
        int retorno = jFileChooser.showOpenDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            try {
                //pega o caminho de cada arquivo selecionado
                selecionados = jFileChooser.getSelectedFiles();
                for (int i = 0; i < selecionados.length; i++) {
                    diretorioArqSel = selecionados[i].toString();
                    BufferedImage imagem;
                    try {
                        imagem = ImageIO.read(new File(diretorioArqSel));
                    } catch (IOException ex) {
                        Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    System.out.println(diretorioArqSel);

                }
                //criar capa do cadastrador
                panelImagens.removeAll();
                
                String dirArquivo = jFileChooser.getSelectedFile().getAbsolutePath();
                arq = jFileChooser.getSelectedFile();
                BufferedImage imagem = ImageIO.read(new File(dirArquivo));
                
                img = new ImageIcon(imagem);
                Image newimg = img.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                ImageIcon newIcon = new ImageIcon(newimg);
                String nomeArquivo = jFileChooser.getName(arq);                
               
                panelImagens.add(new JLabel(img));
                
                panelImagens.repaint();
                
                
                this.pack();
            } catch (IOException ex) {
                Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("Imagem não carregada!");
        }

    }//GEN-LAST:event_btnCarregarImagensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSequenciaDidatic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroSequenciaDidatic().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCarregarImagens;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel panelImagens;
    // End of variables declaration//GEN-END:variables
}
